export const BuilderActions = {
    ADD_FIELD: "ADD_FIELD",

    DELETE_FIELD: "DELETE_FIELD",

    UPDATE_FIELD: "UPDATE_FIELD",

    ADD_CHILD: "ADD_CHILD",

    DELETE_CHILD: "DELETE_CHILD",

    ADD_ARRAY_ITEM: "ADD_ARRAY_ITEM",

    UPDATE_ARRAY_ITEM: "UPDATE_ARRAY_ITEM",

    DELETE_ARRAY_ITEM: "DELETE_ARRAY_ITEM",

    CLEAR: "CLEAR",
};